// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmKFVSEDwjY81QiZFfVyoVRaqHewc9QCs',
    appId: '1:375560768344:web:868af9751f1fbe41a6732d',
    messagingSenderId: '375560768344',
    projectId: 'recipeac7',
    authDomain: 'recipeac7.firebaseapp.com',
    storageBucket: 'recipeac7.appspot.com',
    measurementId: 'G-FH09GTHNDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBqo3d0W5XqS9rpudtuZlmOzHXnDFxy80',
    appId: '1:375560768344:android:e222e61565397988a6732d',
    messagingSenderId: '375560768344',
    projectId: 'recipeac7',
    storageBucket: 'recipeac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpSpxebp70vVfe1XYYYqkoPvmNCmvEaAc',
    appId: '1:375560768344:ios:c0f8add1d4cf2bdfa6732d',
    messagingSenderId: '375560768344',
    projectId: 'recipeac7',
    storageBucket: 'recipeac7.appspot.com',
    iosBundleId: 'com.example.ac7',
  );
}
